version: "3.3"

services:
  mongodb:
    image: mongo:5.0
    ports:
      - 27017:27017
    volumes:
      - ~/apps/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=prova
      - MONGO_INITDB_ROOT_PASSWORD=SECRET

  frontend:
    build: ./evercode-frontend 
    ports: 
      - 3000:3000

  backend:
    build: ./evercode-backend
    ports:
      - 5000:5000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
